import type { Hub, Module } from "./AppContext";

export const initialHubs: Hub[] = [
  {
    id: "YB-2415A7",
    name: "Living Room Hub",
    homeId: "home-1",
    room: "Living Room",
    status: "online",
    icon: "hub",
    firmwareVersion: "v2.1.0",
    ipAddress: "192.168.1.100",
    macAddress: "84:CC:A8:12:34:56",
    wifiSignal: 85,
    connectedSince: new Date(2024, 2, 10, 14, 32),
    lastSeen: new Date(),
    moduleCount: 6,
    onlineModuleCount: 5,
    addedDate: new Date(2024, 1, 10),
  },
  {
    id: "YB-3821B4",
    name: "Kitchen Hub",
    homeId: "home-1",
    room: "Kitchen",
    status: "offline",
    icon: "hub",
    firmwareVersion: "v2.0.8",
    ipAddress: "192.168.1.101",
    macAddress: "84:CC:A8:12:34:57",
    wifiSignal: 60,
    connectedSince: new Date(2024, 1, 15, 10, 20),
    lastSeen: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    moduleCount: 4,
    onlineModuleCount: 0,
    addedDate: new Date(2024, 1, 15),
  },
  {
    id: "YB-5560C9",
    name: "Bedroom Hub",
    homeId: "home-1",
    room: "Bedroom",
    status: "online",
    icon: "hub",
    firmwareVersion: "v2.1.0",
    ipAddress: "192.168.1.102",
    macAddress: "84:CC:A8:12:34:58",
    wifiSignal: 92,
    connectedSince: new Date(2024, 2, 5, 8, 15),
    lastSeen: new Date(),
    moduleCount: 5,
    onlineModuleCount: 5,
    addedDate: new Date(2024, 1, 12),
  },
];

export const initialModules: Module[] = [
  // Living Room Hub modules
  {
    id: "mod-temp-lr",
    name: "Living Room Temperature",
    type: "temperature",
    hubId: "YB-2415A7",
    room: "Living Room",
    homeId: "home-1",
    status: "online",
    feed: "temperature",
    temperature: 24.5,
    lastSeen: new Date(),
  },
  {
    id: "mod-hum-lr",
    name: "Living Room Humidity",
    type: "humidity",
    hubId: "YB-2415A7",
    room: "Living Room",
    homeId: "home-1",
    status: "online",
    feed: "humidity",
    humidity: 65,
    lastSeen: new Date(),
  },
  {
    id: "mod-light-lr",
    name: "Living Room Light Sensor",
    type: "light-sensor",
    hubId: "YB-2415A7",
    room: "Living Room",
    homeId: "home-1",
    status: "online",
    feed: "light",
    lux: 450,
    lastSeen: new Date(),
  },
  {
    id: "mod-fan-lr",
    name: "Living Room Ceiling Fan",
    type: "fan",
    hubId: "YB-2415A7",
    room: "Living Room",
    homeId: "home-1",
    status: "online",
    feed: "fan",
    isOn: true,
    speed: 2,
    lastSeen: new Date(),
  },
  {
    id: "mod-led-lr",
    name: "Living Room RGB LED",
    type: "led",
    hubId: "YB-2415A7",
    room: "Living Room",
    homeId: "home-1",
    status: "online",
    feed: "led",
    isOn: true,
    color: "#8B5CF6",
    brightness: 70,
    lastSeen: new Date(),
  },
  {
    id: "mod-pir-lr",
    name: "Living Room Motion Sensor",
    type: "pir-motion",
    hubId: "YB-2415A7",
    room: "Living Room",
    homeId: "home-1",
    status: "offline",
    feed: "pir",
    motion: false,
    lastSeen: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },

  // Kitchen Hub modules (all offline because hub is offline)
  {
    id: "mod-temp-k",
    name: "Kitchen Temperature",
    type: "temperature",
    hubId: "YB-3821B4",
    room: "Kitchen",
    homeId: "home-1",
    status: "offline",
    feed: "temperature",
    temperature: 26.5,
    lastSeen: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mod-hum-k",
    name: "Kitchen Humidity",
    type: "humidity",
    hubId: "YB-3821B4",
    room: "Kitchen",
    homeId: "home-1",
    status: "offline",
    feed: "humidity",
    humidity: 70,
    lastSeen: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mod-light-k",
    name: "Kitchen Light Sensor",
    type: "light-sensor",
    hubId: "YB-3821B4",
    room: "Kitchen",
    homeId: "home-1",
    status: "offline",
    feed: "light",
    lux: 800,
    lastSeen: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "mod-led-k",
    name: "Kitchen LED",
    type: "led",
    hubId: "YB-3821B4",
    room: "Kitchen",
    homeId: "home-1",
    status: "offline",
    feed: "led",
    isOn: false,
    brightness: 0,
    lastSeen: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },

  // Bedroom Hub modules
  {
    id: "mod-temp-br",
    name: "Bedroom Temperature",
    type: "temperature",
    hubId: "YB-5560C9",
    room: "Bedroom",
    homeId: "home-1",
    status: "online",
    feed: "temperature",
    temperature: 22.0,
    lastSeen: new Date(),
  },
  {
    id: "mod-hum-br",
    name: "Bedroom Humidity",
    type: "humidity",
    hubId: "YB-5560C9",
    room: "Bedroom",
    homeId: "home-1",
    status: "online",
    feed: "humidity",
    humidity: 55,
    lastSeen: new Date(),
  },
  {
    id: "mod-light-br",
    name: "Bedroom Light Sensor",
    type: "light-sensor",
    hubId: "YB-5560C9",
    room: "Bedroom",
    homeId: "home-1",
    status: "online",
    feed: "light",
    lux: 120,
    lastSeen: new Date(),
  },
  {
    id: "mod-fan-br",
    name: "Bedroom Fan",
    type: "fan",
    hubId: "YB-5560C9",
    room: "Bedroom",
    homeId: "home-1",
    status: "online",
    feed: "fan",
    isOn: true,
    speed: 1,
    lastSeen: new Date(),
  },
  {
    id: "mod-led-br",
    name: "Bedroom LED",
    type: "led",
    hubId: "YB-5560C9",
    room: "Bedroom",
    homeId: "home-1",
    status: "online",
    feed: "led",
    isOn: false,
    brightness: 0,
    lastSeen: new Date(),
  },
];
